### ISSUE TITLE
Multiple devices Temperature requests

### ISSUE THREAD

**Issue by ebrger** [MacWyznawca/homebridge-mqtt-temperature-tasmota#12]
Hey, I'm sure I can, but I can't.  I have several Sonoff which I would like to display with the temperature.  With one it also works, from the second he shows me no values. 
 
How do I enter this?  By Mac, IP?  Thank you very much, eric

**Comment by TLCary** [comment]
Each Sonoff should have a unique MQTT Topic (like Sonoff1, Sonoff2).  Then in your config.json file you put in accessories:
```
{	"accessory": "mqtt-temperature-tasmota",
	"name": "Temperature Room 1",
	"url": "mqtt://localhost",
	"topic": "tele/Sonoff1/SENSOR"},
{	"accessory": "mqtt-temperature-tasmota",
	"name": "Temperature Room 2",
	"url": "mqtt://localhost",
	"topic": "tele/Sonoff2/SENSOR"}
```

**Comment by ebrger** [comment]
Thanks, ist works :-)
