### ISSUE TITLE
DS1 etc.

### ISSUE THREAD

**Issue by ochococo** [MacWyznawca/homebridge-mqtt-temperature-tasmota#2]
If you switch multiple DS sensors support in config:

```c++
#define USE_DS18x20                              // Optional using OneWire library for multiple DS18B20 and/or DS18S20 (+2k code)
```

The reading comes in that format: 

```json
{"Time":"2017-04-14T09:12:49", "DS18x20":{"DS1":{"Type":"DS18B20", "Address":"28FFCE6F85160331", "Temperature":25.2}}}
```

And of course the plugin fails.

Notice the `DS1` (I guess it will be DS1, DS2, DS3 etc. for more sensors).

I will try to produce a fix for that soon.

**Comment by kodibrain** [comment]
Hi,
Is there a solution for this?
