### ISSUE TITLE
TH10 showing up but not working in Home app

### ISSUE THREAD

**Issue by chris-008** [MacWyznawca/homebridge-mqtt-temperature-tasmota#6]
hi @MacWyznawca , first off all thanks for the code! 
I managed to add my TH10 with both temperature and humidity icons to Homebridge and the Home app, but they remain in a grey non functional state, therefore I can not toggle or read data. 
MQTT via ip of the TH module (Tasmota) is working fine but nothing happens in the Home app?
This is what is configured in the config.json file:

{
"accessory": "mqtt-temperature-tasmota",
                
                "name": "Humidor",

                "url": "mqtt://192.168.1.7:1883",
                "username": "orangepi",
                "password": "12345",
                
                "topic": "tele/sonoff5/SENSOR",
                
                "activityTopic": "tele/sonoff5/LWT",
                "activityParameter": "Online",
                
                "startCmd": "cmnd/sonoff5/TelePeriod",
                "startParameter": "120",
                
                "sensorPropertyName": "BME280_2",
                
                "manufacturer": "ITEAD",
                "model": "Sonoff TH",
                "serialNumberMAC": "5C:CF:7F:3B:53:F4"
                
        },
{
"accessory": "mqtt-humidity-tasmota",
                
                "name": "Humidor",

                "url": "mqtt://192.168.1.7:1883",
                "username": "orangepi",
                "password": "12345",
                
                "topic": "tele/sonoff5/SENSOR",
                
                "activityTopic": "tele/sonoff5/LWT",
                "activityParameter": "Online",
                
                "startCmd": "cmnd/sonoff5/TelePeriod",
                "startParameter": "120",
                
                "sensorPropertyName": "BME280_2",
                
                "manufacturer": "ITEAD",
                "model": "Sonoff TH",
                "serialNumberMAC": "5C:CF:7F:3B:53:F4"
                
        }

Any idea what might be wrong here? 
Thanks for your help!

**Comment by MacWyznawca** [comment]
Hi!
mqtt://192.168.1.7 <mqtt://192.168.1.7>
Is Your MQTT (Orange) broker addres?
Try witout port number

BME280_2 You give from consola of Sonoff?

Pozdrawiam!

— 
Jaromir (@MacWyznawca)
iOS, macOS and FileMaker developer
<macwyznawca.pl> | qart@me.com 
tel./iMessages: 501 133 157

**Comment by chris-008** [comment]
Thanks for your quick reply :-)
These same lines are working fine on my basic Sonoff modules, would it make a difference for the TH module?
the BME280-2 is a line I found on the web. I am still arranging this sensor sensor (getting GPIO4 ready) , but that's the next step :-)
Right now, a simple ON/OFF toggle is not possible?

**Comment by MacWyznawca** [comment]
I used TH module with my switch plugin.
Themperature too.

You log to console nad copy name of sensot from console (web console of Sonoff).

Pozdrawiam!

— 
Jaromir (@MacWyznawca)
iOS, macOS and FileMaker developer
<macwyznawca.pl> | qart@me.com 
tel./iMessages: 501 133 157

**Comment by MacWyznawca** [comment]
My TH with DHT22 sensor


Pozdrawiam!

— 
Jaromir (@MacWyznawca)
iOS, macOS and FileMaker developer
<macwyznawca.pl> | qart@me.com 
tel./iMessages: 501 133 157

**Comment by chris-008** [comment]
Hi, You gave me a good hint there! Got my topic name messed up it seems, all working fine now, thanks again @MacWyznawca
